name: automerge

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run test
  automerge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Merge
        uses: KeisukeYamashita/auto-renovate-pull-request-merge@v1
